/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELSKYBOX_H__
# define __3D_MODELSKYBOX_H__

POINT point_skybox[] = {
       POStoFIXED(0, -240, -368),
       POStoFIXED(0, 240, -368),
       POStoFIXED(318.697, -240, -184),
       POStoFIXED(318.697, 240, -184),
       POStoFIXED(318.697, -240, 184),
       POStoFIXED(318.697, 240, 184),
       POStoFIXED(-3.05176e-005, -240, 368),
       POStoFIXED(-3.05176e-005, 240, 368),
       POStoFIXED(-318.697, -240, 184),
       POStoFIXED(-318.697, 240, 184),
       POStoFIXED(-318.697, -240, -184),
       POStoFIXED(-318.697, 240, -184),
};

POLYGON polygon_skybox[] = {
       NORMAL(-0.5, 0, 0.866013), VERTICES(1, 3, 2, 0),
       NORMAL(-1, 0, 0), VERTICES(3, 5, 4, 2),
       NORMAL(-0.499985, 0, -0.866028), VERTICES(5, 7, 6, 4),
       NORMAL(0.5, 0, -0.866013), VERTICES(7, 9, 8, 6),
       NORMAL(1, 0, 0), VERTICES(9, 11, 10, 8),
       NORMAL(0.5, 0, 0.866013), VERTICES(11, 1, 0, 10),
};

ATTR attribute_skybox[] = {
       ATTRIBUTE(Single_Plane, SORT_MAX, 65, LUTidx(65), CL32KRGB | No_Gouraud, CL32KRGB | MESHon , sprNoflip, No_Option|UseNearClip),
       ATTRIBUTE(Single_Plane, SORT_MAX, 65, LUTidx(65), CL32KRGB | No_Gouraud, CL32KRGB | MESHon , sprNoflip, No_Option|UseNearClip),
       ATTRIBUTE(Single_Plane, SORT_MAX, 65, LUTidx(65), CL32KRGB | No_Gouraud, CL32KRGB | MESHon , sprNoflip, No_Option|UseNearClip),
       ATTRIBUTE(Single_Plane, SORT_MAX, 65, LUTidx(65), CL32KRGB | No_Gouraud, CL32KRGB | MESHon , sprNoflip, No_Option|UseNearClip),
       ATTRIBUTE(Single_Plane, SORT_MAX, 65, LUTidx(65), CL32KRGB | No_Gouraud, CL32KRGB | MESHon , sprNoflip, No_Option|UseNearClip),
       ATTRIBUTE(Single_Plane, SORT_MAX, 65, LUTidx(65), CL32KRGB | No_Gouraud, CL32KRGB | MESHon , sprNoflip, No_Option|UseNearClip),
};

VECTOR normal_skybox[] = {
       POStoFIXED(0, 0, 0.866013),
       POStoFIXED(0, 0, 0.866013),
       POStoFIXED(-0.75, 0, 0.432999),
       POStoFIXED(-0.75, 0, 0.432999),
       POStoFIXED(-0.749985, 0, -0.433014),
       POStoFIXED(-0.749985, 0, -0.433014),
       POStoFIXED(0, 0, -0.866013),
       POStoFIXED(0, 0, -0.866013),
       POStoFIXED(0.75, 0, -0.432999),
       POStoFIXED(0.75, 0, -0.432999),
       POStoFIXED(0.75, 0, 0.432999),
       POStoFIXED(0.75, 0, 0.432999),
};

XPDATA xpdata_skybox[] = {
   {
       point_skybox, sizeof(point_skybox)/sizeof(POINT),
       polygon_skybox, sizeof(polygon_skybox)/sizeof(POLYGON),
       attribute_skybox,
       normal_skybox
  }
};

#endif /* !__3D_MODELSKYBOX_H__ */
